# Generated by Django 2.2 on 2020-01-16 23:03

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200111_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='users/profile_images'),
        ),
    ]
