# Generated by Django 2.2 on 2020-01-05 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200104_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='video',
        ),
    ]
