# Generated by Django 2.2 on 2020-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_coursevideo_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDocuments',
            new_name='CourseDocument',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='rreleased_on',
            new_name='released_on',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='video',
            field=models.URLField(default='Null', max_length=255),
        ),
    ]
