# Generated by Django 2.2 on 2020-01-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200107_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedocument',
            name='text',
        ),
    ]
