# Generated by Django 2.2 on 2020-01-07 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_coursedocument_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocument',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_document', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='course_files',
            field=models.FileField(max_length=250, null=True, upload_to='course/course_files'),
        ),
        migrations.AlterField(
            model_name='coursedocument',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_video', to='course.CourseVideo'),
        ),
    ]
