# Generated by Django 2.2 on 2020-01-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200107_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='video',
            field=models.TextField(default='Null'),
        ),
    ]
