# Generated by Django 2.2 on 2020-01-10 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0007_auto_20200108_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('video', models.CharField(max_length=250)),
                ('video_decription', models.TextField()),
                ('video_documents', models.FileField(max_length=250, upload_to='video_tutorials/documents')),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
