# Generated by Django 2.2 on 2020-01-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_videotutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTutorial',
        ),
    ]
