# Generated by Django 2.2 on 2019-12-19 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_authur', models.TextField(default='Add book description')),
                ('book_title', models.CharField(max_length=250)),
                ('book_type', models.CharField(choices=[('PP', 'Past Papers'), ('TB', 'Text Book'), ('EZ', 'Examination Results'), ('SE', 'Solved Exercices')], max_length=2)),
                ('level', models.CharField(choices=[('SS', 'Secondary Schools'), ('HS', 'High School'), ('U', 'University')], max_length=2)),
                ('departments', models.CharField(choices=[('SS', 'Secondary School Science'), ('SA', 'Secondary School Art')], max_length=2)),
                ('price', models.IntegerField(default=0)),
                ('file', models.FileField(max_length=250, upload_to='books/files')),
                ('book_front_cover', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='books/images')),
                ('book_back_cover', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='books/images')),
                ('description', models.TextField(default='Add book description')),
                ('book_created_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
