# Generated by Django 2.2 on 2020-04-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_authur_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_created_date',
        ),
    ]
