# Generated by Django 2.2 on 2019-12-18 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=250)),
                ('registered_id', models.IntegerField()),
                ('region', models.CharField(max_length=250)),
                ('division', models.CharField(max_length=250)),
                ('sub_division', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('quater', models.CharField(max_length=250)),
                ('creation_date', models.DateField(max_length=250)),
                ('school_type', models.CharField(choices=[('P', 'Primary school'), ('S', 'Secondary School'), ('U', 'University'), ('Es', 'Evening School')], max_length=1)),
                ('logo', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='logo')),
                ('description', models.TextField()),
                ('email', models.EmailField(default='example@school.com', max_length=254)),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
