# Generated by Django 2.2 on 2019-12-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20191219_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='user',
        ),
    ]
