# Generated by Django 2.2 on 2019-12-19 14:48

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_classe_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Femail')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('students_phone', models.IntegerField()),
                ('matricule', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('HE', 'Hardware Engineering'), ('SE', 'Software Engineering')], max_length=2)),
                ('teachers_image', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='student/images')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Classe')),
            ],
        ),
    ]
