# Generated by Django 2.2 on 2019-12-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
