# Generated by Django 2.2 on 2019-12-19 15:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('school', '0007_auto_20191219_1550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classe',
            new_name='Class',
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class',
                     'verbose_name_plural': 'Classes'},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='students_phone',
            new_name='teachers_phone',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student_class',
        ),
    ]
