# Generated by Django 2.2 on 2019-12-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20191219_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='user',
            new_name='ceated_by',
        ),
    ]
