# Generated by Django 2.2 on 2019-12-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20191228_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='ceated_by',
            new_name='created_by',
        ),
    ]
