# Generated by Django 2.2 on 2019-12-30 22:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20191230_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='school/logo'),
        ),
    ]
