# Generated by Django 2.2 on 2019-12-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20191230_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
