# Generated by Django 2.2 on 2019-12-31 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20191231_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school.School'),
        ),
    ]
