# Generated by Django 2.2 on 2020-01-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20191231_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(default='teacher paymens', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='school.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('amount', models.IntegerField()),
                ('class_for_fees', models.ForeignKey(default='All classes', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='school.Class')),
                ('school', models.ForeignKey(default='no_school', on_delete=django.db.models.deletion.CASCADE, related_name='fees_for_school', to='school.School')),
            ],
        ),
    ]
