# Generated by Django 2.2 on 2020-01-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_fees_payments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
    ]
