# Generated by Django 2.2 on 2020-01-04 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20200104_1236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fees',
            new_name='Fee',
        ),
    ]
