# Generated by Django 2.2 on 2020-01-14 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20200114_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_class',
            field=models.ForeignKey(default='No class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
    ]
