# Generated by Django 2.2 on 2020-01-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20200114_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_class',
            field=models.ForeignKey(default='Class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
    ]
