# Generated by Django 2.2 on 2020-01-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20200114_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_class',
            field=models.ForeignKey(default='teachers_class', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.Class'),
        ),
    ]
