# Generated by Django 2.2 on 2020-01-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20200114_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('P', 'Primary school'), ('SS', 'Secondary School'), ('U', 'University'), ('Es', 'Evening School')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Secondary School Science', 'Secondary School Science'), ('Secondary School Art ', 'Secondary School Art'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy'), ('Transport and Logistics', 'Transport and Logistics'), ('Computer Engineering', 'Computer Engineering'), ('Telecommunication', 'Telecommunication')], max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(choices=[('Secondary School Science', 'Secondary School Science'), ('Secondary School Art ', 'Secondary School Art'), ('Marketing', 'Marketing'), ('Accountancy', 'Accountancy'), ('Transport and Logistics', 'Transport and Logistics'), ('Computer Engineering', 'Computer Engineering'), ('Telecommunication', 'Telecommunication')], max_length=100),
        ),
    ]
