# Generated by Django 2.2 on 2020-01-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_auto_20200119_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Primary school', 'Primary school'), ('Secondary School', 'Secondary School'), ('Pofessional School', 'Professional School'), ('University', 'University'), ('Evening School', 'Evening School')], max_length=100),
        ),
    ]
