# Generated by Django 2.2 on 2020-01-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_auto_20200119_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('Good', 'good'), ('Bad', 'Bad'), ('Critical', 'Critical')], default='Good', max_length=100),
        ),
    ]
