# Generated by Django 2.2 on 2020-01-10 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(default='default.png', upload_to='tutorials/videos')),
                ('title', models.CharField(max_length=250)),
                ('video', models.CharField(max_length=250)),
                ('video_decription', models.TextField()),
                ('video_documents', models.FileField(max_length=250, upload_to='video_tutorials/documents')),
                ('price', models.IntegerField()),
                ('created_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
