# Generated by Django 2.2 on 2020-01-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subscribers',
            field=models.IntegerField(default=0),
        ),
    ]
