# Generated by Django 2.2 on 2020-01-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_video_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='author',
            new_name='authur',
        ),
    ]
