# Generated by Django 2.2 on 2020-01-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20200110_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(),
        ),
    ]
