# Generated by Django 2.2 on 2020-01-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20200110_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_decription',
            new_name='video_description',
        ),
    ]
